@host = http://localhost:8080

### 계좌 생성 (201)
POST {{host}}/api/v1/accounts
Content-Type: application/json

{
  "accountNumber": "123456789012",
  "ownerName": "홍길동"
}

> {%
  client.global.set("accountId", response.body.accountId);
%}

### (준비) 계좌 생성 이체 대상 계좌 (201)
POST {{host}}/api/v1/accounts
Content-Type: application/json

{
  "accountNumber": "999999999999",
  "ownerName": "김철수"
}

### 계좌 상세 조회 (200)
GET {{host}}/api/v1/accounts/{{accountId}}

### 계좌 생성 중복 (409)
POST {{host}}/api/v1/accounts
Content-Type: application/json

{
  "accountNumber": "123456789012",
  "ownerName": "홍길동"
}

### 계좌 삭제(해지) (204)
DELETE {{host}}/api/v1/accounts/{{accountId}}

### 없는 계좌 조회 (404)
GET {{host}}/api/v1/accounts/99999999

### 없는 계좌 삭제 (404)
DELETE {{host}}/api/v1/accounts/99999999

