@host = http://localhost:8080

### (준비 1) 계좌 생성 (201)
POST {{host}}/api/v1/accounts
Content-Type: application/json

{
  "ownerName": "홍길동",
  "phoneNumber": "01012345678"
}

> {%
  client.global.set("accountId", response.body.data.accountId);
  client.global.set("accountNumber", response.body.data.accountNumber);
%}

### (준비 2) 계좌 생성 - 이체 대상 계좌 (201)
POST {{host}}/api/v1/accounts
Content-Type: application/json

{
  "ownerName": "김철수",
  "phoneNumber": "01098765432"
}

> {%
  client.global.set("targetAccountNumber", response.body.data.accountNumber);
%}

### 계좌 상세 조회 (200)
GET {{host}}/api/v1/accounts/{{accountId}}

### 없는 계좌 조회 (404)
GET {{host}}/api/v1/accounts/99999999

### 없는 계좌 삭제 (404)
DELETE {{host}}/api/v1/accounts/99999999

### 계좌 삭제(해지) (마지막에 테스트 권장) (204)
DELETE {{host}}/api/v1/accounts/{{accountId}}